### ISSUE TITLE
auth2/authorization/qq 无法访问，控制器再哪里定义的?

### ISSUE THREAD

**Issue by nsioo** [justauth/justauth-spring-boot-security-starter#1]
spring cloud项目，

2020-11-22 23:08:25.319 ERROR 13872 --- [  XNIO-1 task-3] io.undertow.request                      : UT005023: Exception handling request to /auth2/authorization/qq

java.lang.NullPointerException: null
	at top.dcenter.ums.security.core.oauth.filter.redirect.Auth2DefaultRequestRedirectFilter.doFilterInternal

**Comment by ZeroOrInfinity** [comment]
看错误提示应该是你没有配置与 qq 第三方的相关的属性配置, 相关配置请参考示例代码
```yml
ums:
  oauth:
    # 第三方服务商: providerId, 支持所有 JustAuth 支持的第三方授权登录, 目前支持有 32 家第三方授权登录
    qq:
      # 根据是否有设置 clientId 来动态加载相应 JustAuth 的 AuthXxxRequest
      client-id: xxxx你申请的client-id
      client-secret: 953dd你申请的client-secret
      # 是否需要申请 unionId，默认: false. 目前只针对qq登录 注：qq授权登录时，获取 unionId 需要单独发送邮件申请权限。如果个人开发者账号中申请了该权限，可以将该值置为true，在获取openId时就会同步获取unionId 参考链接：http://wiki.connect.qq.com/unionid%E4%BB%8B%E7%BB%8D
      union-id: true
```

如果你配置了相关配置, 还是报错, 那请提出详细的配置与错误提示

**Comment by ZeroOrInfinity** [comment]
没有控制器, 通过过滤器来处理 OAuth2 Login 逻辑, 登录 uri 可以通过配置属性自定义:
```yml
ums:
  oauth:
    # 第三方登录授权登录 url 前缀, 不包含 ServletContextPath，默认为 /auth2/authorization.
    auth-login-url-prefix: /auth2/authorization
    # 第三方登录回调处理 url 前缀 ，也就是 RedirectUrl 的前缀, 不包含 ServletContextPath，默认为 /auth2/login.
    redirect-url-prefix: /auth2/login
```
